name: Production Deployment via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Code to Contabo VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 31.220.84.34
          username: root
          key: ${{ secrets.SERVER_SSH_KEY_NSP }}
          port: 22  # Change this if your server uses a custom SSH port instead of 22
          script: |
            echo "=== Syncing repository updates ==="
            cd /www/wwwroot/newsuperprime.sa/wp-content/themes/newsuperprime-theme-3
            git config --global --add safe.directory /www/wwwroot/newsuperprime.sa/wp-content/themes/newsuperprime-theme-3
            git fetch --all
            git reset --hard origin/main
            chown -R www:www /www/wwwroot/newsuperprime.sa/wp-content/themes/newsuperprime-theme-3
            echo "=== Deploy finished successfully ==="